version: "3"

services:
  apisix:
    image: apache/apisix:3.9.1-debian
    volumes:
      - ./scripts/apisix_conf.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9090:9090/tcp"
      - "9091:9091/tcp"
      - "9180:9180/tcp"
    networks:
      apisix:

  etcd:
    image: rancher/coreos-etcd:v3.4.15-arm64
    user: root
    environment:
      ETCD_UNSUPPORTED_ARCH: "arm64"
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_DATA_DIR: "/etcd-data"
    networks:
      apisix:

  web-server-1:
    image: nginx:alpine
    networks:
      apisix:

  web-server-2:
    image: nginx:alpine
    networks:
      apisix:

  redis-1:
    image: redis:alpine
    networks:
      apisix:

  apisix-standalone:
    image: apache/apisix:3.9.1-debian
    volumes:
      - ./scripts/apisix_standalone:/usr/local/apisix/conf
      - ./plugin_w/pkg:/wasm_plugin
    ports:
      - "4100:9180/tcp"
      - "4000:9080/tcp"
    networks:
      apisix:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./scripts/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - apisix

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 7050:3000
    networks:
      - apisix

networks:
  apisix:
    driver: bridge
