version: "3"

services:
  apisix:
    image: apache/apisix:3.9.1-debian
    restart: always
    volumes:
      - ./scripts/apisix_conf.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9090:9090/tcp"
      - "9180:9180/tcp"
    networks:
      apisix:

  etcd:
    image: rancher/coreos-etcd:v3.4.15-arm64
    user: root
    restart: always
    environment:
      ETCD_UNSUPPORTED_ARCH: "arm64"
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_DATA_DIR: "/etcd-data"
    networks:
      apisix:

  web_server_1:
    image: nginx:alpine
    restart: always
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
