// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyType } from "./PropertyType";
import type { Required } from "./Required";

export type EntityFields = {
  default_value: null | string;
  description: string;
  hidden: boolean;
  is_required: Required;
  name: string;
  property_type: PropertyType;
};
