// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginEntities } from "./PluginEntities";
import type { PluginOption } from "./PluginOption";

export type PluginDefinition = {
  entities: PluginEntities[];
  name: string;
  options: PluginOption[];
};
