// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginPropertyType } from "./PluginPropertyType";

export type PluginOption = {
  default_value: null | string;
  description: string;
  is_required: boolean;
  name: string;
  property_type: PluginPropertyType;
};
