// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerInfo = {
  apisix_url: string;
  has_auth: boolean;
  is_standalone: boolean;
};
