deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
wasm:
  plugins:
    - name: wasm_log
      priority: 10
      file: /wasm_plugin/apisix_admin_panel_plugin_example_bg.wasm
      http_request_phase: access
#END
