on:
  workflow_dispatch:

name: Checks

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run checks
        run: |
          nix develop path:$(pwd) -c rustup install stable
          nix develop path:$(pwd) -c bash scripts/checks.sh
