name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: igncp
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build script
        run: |
          nix develop path:$(pwd) -c rustup install stable
      - name: Build docker image
        run: |
          nix develop path:$(pwd) -c bash scripts/release.sh
